/*
 * app_config.h
 * Responsibility: Centralized compile-time configuration for the modular app.
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifndef APP_DEBUG
#define APP_DEBUG (1)
#endif

#define APP_VERBOSE APP_DEBUG

#define APP_SOC_FC_FREQ_HZ (100000000)
#define APP_SOC_CL_FREQ_HZ (100000000)

#define APP_NET_ARENA_BYTES (412000u)
#define APP_NET_OUTPUT_BYTES (12u)
#ifndef APP_ALLOCATE_ARENA_BEFORE_NETWORK_INIT
#define APP_ALLOCATE_ARENA_BEFORE_NETWORK_INIT (0)
#endif
#ifndef APP_L2_PROBE_START_BYTES
#define APP_L2_PROBE_START_BYTES (524288u)
#endif
#ifndef APP_L2_PROBE_STEP_BYTES
#define APP_L2_PROBE_STEP_BYTES (1024u)
#endif
#ifndef APP_L2_PROBE_MIN_BYTES
#define APP_L2_PROBE_MIN_BYTES (1024u)
#endif
#define APP_NET_INPUT_W (128)
#define APP_NET_INPUT_H (128)
#ifndef APP_NET_INPUT_C
#define APP_NET_INPUT_C (1)
#endif
#define APP_NET_INPUT_BYTES ((APP_NET_INPUT_W) * (APP_NET_INPUT_H) * (APP_NET_INPUT_C))

#define APP_CAMERA_WIDTH (324)
#define APP_CAMERA_HEIGHT (244)
#define APP_CAMERA_FRAME_BYTES ((APP_CAMERA_WIDTH) * (APP_CAMERA_HEIGHT))
#define APP_CAMERA_CAPTURE_TIMEOUT_US (500000u)
#define APP_CAMERA_IMG_ORIENTATION_REG (0x0101u)

#ifndef APP_LOG_SUMMARY_EVERY_N_FRAMES
#define APP_LOG_SUMMARY_EVERY_N_FRAMES (10u)
#endif
#ifndef APP_LOG_HEARTBEAT_INTERVAL_US
#define APP_LOG_HEARTBEAT_INTERVAL_US (1000000u)
#endif
#ifndef APP_LOG_OUTPUT_DUMP
#define APP_LOG_OUTPUT_DUMP (0)
#endif
#ifndef APP_FOLLOW_OUTPUT_Q_SCALE
#define APP_FOLLOW_OUTPUT_Q_SCALE (32768.0f)
#endif
#ifndef APP_FOLLOW_VISIBLE_CONFIDENCE_THRESHOLD
#define APP_FOLLOW_VISIBLE_CONFIDENCE_THRESHOLD (0.50f)
#endif
#ifndef APP_ENABLE_CPX_APP_PACKET_TX
#define APP_ENABLE_CPX_APP_PACKET_TX (0)
#endif
#ifndef APP_GENERATED_NETWORK_VERBOSE
#define APP_GENERATED_NETWORK_VERBOSE (0)
#endif

#define APP_IO_DUMP_BYTES (64u)
#define APP_PACKET_MAGIC (0xA5u)
#define APP_PACKET_VERSION (0x01u)

#endif /* APP_CONFIG_H */
